spring:
  datasource:
    url: jdbc:h2:mem:emar
    driver-class-name: org.h2.Driver
    username: sa
    platform: org.hibernate.dialect.H2Dialect
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
springdoc:
  api-docs:
    path: /api-docs